spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    initialization-mode: always
    platform: postgres
    url: jdbc:postgresql://127.0.0.1:5432/dual
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
